robot_cfg:
  name: g1
  urdf_path: g1/urdf/g1_29dof_with_hand.urdf
  mesh_path: g1/meshes/
  body_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
  left_arm_indices: [15, 16, 17, 18, 19, 20, 21]
  right_arm_indices: [29, 30, 31, 32, 33, 34, 35]
  left_hand_indices: [22, 23, 24, 25, 26, 27, 28]
  right_hand_indices: [36, 37, 38, 39, 40, 41, 42]

  pd:
    body_kp: 600
    body_kd: 60
    arm_kp: 80
    arm_kd: 8
    hand_kp: 30
    hand_kd: 0.5

  head_pos: [ 0.1, 0.0, 0.4 ]
  left_wrist_name: left_palm_keypoint
  right_wrist_name: right_palm_keypoint

  body:
    in_lp_alpha: 0.9

  arm:
    dt: 0.016667

    scaling_factor: 0.7
    base_damping: 1e-2
    max_damping: 0.1
    eps: 1e-2

    in_lp_alpha: 0.8
    out_lp_alpha: 0.8

    left_links: ["left_elbow", "left_wrist", "left_hand_palm"]
    right_links: ["right_elbow", "right_wrist", "right_hand_palm"]

  hand:
    left_hand:
      scaling_factor: 1.0
      in_lp_alpha: 0.8
      out_lp_alpha: 0.8

      target_origin_link_names: [  "left_palm_keypoint", "left_palm_keypoint", "left_palm_keypoint", "left_two_tip", "left_two_tip"]
      target_task_link_names: [ "left_two_tip", "left_four_tip", "left_six_tip", "left_four_tip", "left_six_tip" ]
      target_link_human_indices: [ [0, 0, 0, 4, 4], [4, 9, 14, 9, 14] ]
      dex_pilot: [None, None, None, ['<=', 0.03, 1e-4, 200], ['<=', 0.03, 1e-4, 200]]

    right_hand:
      scaling_factor: 1.0
      in_lp_alpha: 0.8
      out_lp_alpha: 0.8

      target_origin_link_names: [ "right_palm_keypoint", "right_palm_keypoint", "right_palm_keypoint", "right_two_tip", "right_two_tip"]
      target_task_link_names: [ "right_two_tip", "right_four_tip", "right_six_tip", "right_four_tip", "right_six_tip" ]
      target_link_human_indices: [ [0, 0, 0, 4, 4], [4, 9, 14, 9, 14] ]
      dex_pilot: [None, None, None, ['<=', 0.03, 1e-4, 200], ['<=', 0.03, 1e-4, 200]]

