robot_cfg:
  name: g1_dex3
  urdf_path: g1_dex3/urdf/g1_29dof_with_hand_rev_1_0_new.urdf
  xml_path: g1_dex3/
  mesh_path: g1_dex3/meshes/
  robot_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42]
  body_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
  left_arm_indices: [15, 16, 17, 18, 19, 20, 21]
  right_arm_indices: [29, 30, 31, 32, 33, 34, 35]
  left_hand_indices: [22, 23, 24, 25, 26, 27, 28]
  right_hand_indices: [36, 37, 38, 39, 40, 41, 42]
  waist_index: [12]
  torso_indices: [12, 13, 14]

  arm_motor_indices: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42]

  head_pos: [ 0.2, 0.0, 0.5 ]
  left_wrist_name: left_wrist_roll_link
  right_wrist_name: right_wrist_roll_link

  upper_torque_limits: [88, 139, 88, 139, 50, 50,
                  88, 139, 88, 139, 50, 50,
                  88, 50, 50,
                  25, 25, 25, 25, 25, 5, 5,
                  2.45, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4,
                  25, 25, 25, 25, 25, 5, 5,
                  2.45, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4]

  lower_torque_limits: [-88, -139, -88, -139, -50, -50,
                  -88, -139, -88, -139, -50, -50,
                  -88, -50, -50,
                  -25, -25, -25, -25, -25, -5, -5,
                  -2.45, -1.4, -1.4, -1.4, -1.4, -1.4, -1.4,
                  -25, -25, -25, -25, -25, -5, -5,
                  -2.45, -1.4, -1.4, -1.4, -1.4, -1.4, -1.4]

  body:
    in_lp_alpha: 0.9

  arm:
    dt: 0.016667

    scaling_factor: 1.0
    base_damping: 1e-2
    max_damping: 1e-2
    eps: 1e-2

    in_lp_alpha: 0.5
    out_lp_alpha: 0.5

  hand:
    left_hand:
      # scaling_factor: [ 1.1, 1.1, 1.1, 1.1, 1.2, 1.0, 1.0 ]
      scaling_factor: [ 1.0, 1.0, 1.0, 1.0, 1.0 ]
      in_lp_alpha: 0.5
      out_lp_alpha: 0.5

      # target_origin_link_names: [  "L_hand_base_link", "L_hand_base_link", "L_hand_base_link", "L_hand_base_link", "L_hand_base_link", "L_thumb_tip", "L_thumb_tip" ]
      # target_task_link_names: [ "L_thumb_tip", "L_index_tip", "L_middle_tip", "L_ring_tip", "L_pinky_tip", "L_index_tip", "L_middle_tip" ]
      # target_link_human_indices: [ [0, 0, 0, 0, 0, 4, 4], [4, 9, 14, 19, 24, 9, 14] ]
      # dex_pilot: [None, None, None, None, None, ['<=', 0.03, 1e-4, 200], ['<=', 0.03, 1e-4, 200]]
      target_origin_link_names: [  "left_hand_palm_link", "left_hand_palm_link", "left_hand_palm_link", "left_hand_thumb_0_link", "left_hand_thumb_0_link" ]
      target_task_link_names: [ "left_hand_thumb_2_link", "left_hand_middle_1_link", "left_hand_index_1_link", "left_hand_middle_1_link", "left_hand_index_1_link" ]
      target_link_human_indices: [ [0, 0, 0, 4, 4], [4, 9, 14, 9, 14] ]
      dex_pilot: [None, None, None, ['<=', 0.03, 1e-4, 200], ['<=', 0.03, 1e-4, 200]]

      # mimic:
      #   parent_joints: ["L_thumb_proximal_pitch_joint", "L_thumb_proximal_pitch_joint", "L_index_proximal_joint", "L_middle_proximal_joint", "L_ring_proximal_joint", "L_pinky_proximal_joint"]
      #   child_joints: ["L_thumb_intermediate_joint", "L_thumb_distal_joint", "L_index_intermediate_joint", "L_middle_intermediate_joint", "L_ring_intermediate_joint", "L_pinky_intermediate_joint"]
      #   mimic_factors: [1.6, 2.4, 1, 1, 1, 1]

    right_hand:
      # scaling_factor: [ 1.1, 1.1, 1.1, 1.1, 1.2, 1.0, 1.0 ]
      scaling_factor: [ 1.1, 1.1, 1.1, 1.0, 1.0 ]
      in_lp_alpha: 0.5
      out_lp_alpha: 0.5

      target_origin_link_names: [ "right_hand_palm_link", "right_hand_palm_link", "right_hand_palm_link", "right_hand_thumb_0_link", "right_hand_thumb_0_link" ]
      target_task_link_names: [ "right_hand_thumb_2_link", "right_hand_middle_1_link", "right_hand_index_1_link", "right_hand_middle_1_link", "right_hand_index_1_link" ]
      target_link_human_indices: [ [0, 0, 0, 4, 4], [4, 9, 14, 9, 14] ]
      dex_pilot: [None, None, None, ['<=', 0.015, 1e-4, 200], ['<=', 0.015, 1e-4, 200]]

      # mimic:
      #   parent_joints: [ "R_thumb_proximal_pitch_joint", "R_thumb_proximal_pitch_joint", "R_index_proximal_joint", "R_middle_proximal_joint", "R_ring_proximal_joint", "R_pinky_proximal_joint" ]
      #   child_joints: [ "R_thumb_intermediate_joint", "R_thumb_distal_joint", "R_index_intermediate_joint", "R_middle_intermediate_joint", "R_ring_intermediate_joint", "R_pinky_intermediate_joint" ]
      #   mimic_factors: [ 1.6, 2.4, 1, 1, 1, 1 ]