robot_cfg:
  name: gr1
  body_indices: [0, 1, 2, 3, 4, 5, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]
  left_arm_indices: [6, 7, 8, 9, 10, 11, 12]
  right_arm_indices: [14, 15, 16, 17, 18, 19, 20]
  left_hand_indices: [13]
  right_hand_indices: [21]

  body:
    # model_path: None
    low_pass_alpha: 0.9

  arm:
    dt: 0.016667
    urdf_path: gr1_jaw/urdf/GR1T1.urdf
    mesh_path: gr1_jaw/meshes

    collision: False
    scaling_factor: 1.1
    ik_damping: 1e-3
    eps: 1e-2
    left_wrist: l_hand_keypoint
    right_wrist: r_hand_keypoint
    locked_joints: ['joint_waist_yaw', 'joint_waist_pitch', 'joint_waist_roll']

    low_pass_alpha: 0.5

  hand:
    scaling_factor: 1.0
    low_pass_alpha: 0.5

    left_hand:
      urdf_path: gr1_jaw/urdf/left_jaw.urdf
      wrist_link_name: "l_hand_pitch"

      target_origin_link_names: [ "l_jaw_tip0" ]
      target_task_link_names: [ "l_jaw_tip1" ]
      target_link_human_indices: [ [ 4 ], [ 9 ] ]
      dex_pilot: [['<=', 0.03, 1e-4, 200]]

    right_hand:
      urdf_path: gr1_jaw/urdf/right_jaw.urdf
      wrist_link_name: "r_hand_pitch"

      target_origin_link_names: [ "r_jaw_tip0" ]
      target_task_link_names: [ "r_jaw_tip1" ]
      target_link_human_indices: [ [ 4 ], [ 9 ] ]
      dex_pilot: [['<=', 0.03, 1e-4, 200]]