robot_cfg:
  name: gr1_jaw
  urdf_path: gr1_jaw/urdf/GR1T1.urdf
  body_indices: [0, 1, 2, 3, 4, 5, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]
  left_arm_indices: [6, 7, 8, 9, 10, 11, 12]
  right_arm_indices: [14, 15, 16, 17, 18, 19, 20]
  left_hand_indices: [13]
  right_hand_indices: [21]
  waist_index: 0

  head_pos: [ 0.2, 0.0, 0.5 ]
  left_wrist_name: l_hand_keypoint
  right_wrist_name: r_hand_keypoint

  body:
    in_lp_alpha: 0.9

  arm:
    dt: 0.016667

    scaling_factor: 1.0
    base_damping: 1e-4
    max_damping: 0.1
    eps: 1e-2

    in_lp_alpha: 0.5
    out_lp_alpha: 0.5

  ee_type: "gripper"
  gripper_type: "1dof"
  human_hand_indices: [4, 9]

  hand:
    left_hand:
      scaling_factor: 1.0
      in_lp_alpha: 0.5
      out_lp_alpha: 0.5

      target_origin_link_names: [ "l_jaw_tip0" ]
      target_task_link_names: [ "l_jaw_tip1" ]
      target_link_human_indices: [ [ 4 ], [ 9 ] ]
      dex_pilot: [['<=', 0.03, 1e-4, 200]]

    right_hand:
      scaling_factor: 1.0
      in_lp_alpha: 0.5
      out_lp_alpha: 0.5

      target_origin_link_names: [ "r_jaw_tip0" ]
      target_task_link_names: [ "r_jaw_tip1" ]
      target_link_human_indices: [ [ 4 ], [ 9 ] ]
      dex_pilot: [['<=', 0.03, 1e-4, 200]]
  
  ee:
    left_ee:
      gripper_range: [0.0, 1.6]

    right_ee:
      gripper_range: [0.0, -1.6]