robot_cfg:
  name: h1_inspire
  urdf_path: h1_inspire/urdf/h1_inspire_no_lower_dexurdf.urdf
  mesh_path: h1_inspire/meshes/
  body_indices: [0]
  left_arm_indices: [1, 2, 3, 4, 5, 6, 7]
  right_arm_indices: [20, 21, 22, 23, 24, 25, 26]
  left_hand_indices: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  right_hand_indices: [27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38]

  pd:
    body_kp: 600
    body_kd: 60
    arm_kp: 80
    arm_kd: 8
    hand_kp: 30
    hand_kd: 0.5

  head_pos: [ 0.1, 0.0, 0.65 ]
  left_wrist_name: L_hand_base_link
  right_wrist_name: R_hand_base_link

  body:
    in_lp_alpha: 0.9

  arm:
    dt: 0.016667

    scaling_factor: 1.1
    base_damping: 1e-2
    max_damping: 1e-2
    eps: 1e-2

    in_lp_alpha: 0.8
    out_lp_alpha: 0.8

    left_links: ["left_elbow", "left_wrist", "L_hand"]
    right_links: ["right_elbow", "right_wrist", "R_hand"]

  hand:
    left_hand:
      scaling_factor: [ 1.1, 1.1, 1.1, 1.1, 1.2, 1.0, 1.0 ]
      in_lp_alpha: 0.8
      out_lp_alpha: 0.8

      target_origin_link_names: [  "L_hand_base_link", "L_hand_base_link", "L_hand_base_link", "L_hand_base_link", "L_hand_base_link", "L_thumb_tip", "L_thumb_tip" ]
      target_task_link_names: [ "L_thumb_tip", "L_index_tip", "L_middle_tip", "L_ring_tip", "L_pinky_tip", "L_index_tip", "L_middle_tip" ]
      target_link_human_indices: [ [0, 0, 0, 0, 0, 4, 4], [4, 9, 14, 19, 24, 9, 14] ]
      dex_pilot: [None, None, None, None, None, ['<=', 0.03, 1e-4, 200], ['<=', 0.03, 1e-4, 200]]

      mimic:
        parent_joints: ["L_thumb_proximal_pitch_joint", "L_thumb_proximal_pitch_joint", "L_index_proximal_joint", "L_middle_proximal_joint", "L_ring_proximal_joint", "L_pinky_proximal_joint"]
        child_joints: ["L_thumb_intermediate_joint", "L_thumb_distal_joint", "L_index_intermediate_joint", "L_middle_intermediate_joint", "L_ring_intermediate_joint", "L_pinky_intermediate_joint"]
        mimic_factors: [1.6, 2.4, 1, 1, 1, 1]

    right_hand:
      scaling_factor: [ 1.1, 1.1, 1.1, 1.1, 1.2, 1.0, 1.0 ]
      in_lp_alpha: 0.8
      out_lp_alpha: 0.8

      target_origin_link_names: [ "R_hand_base_link", "R_hand_base_link", "R_hand_base_link", "R_hand_base_link", "R_hand_base_link", "R_thumb_tip", "R_thumb_tip"]
      target_task_link_names: [ "R_thumb_tip", "R_index_tip", "R_middle_tip", "R_ring_tip", "R_pinky_tip", "R_index_tip", "R_middle_tip" ]
      target_link_human_indices: [ [0, 0, 0, 0, 0, 4, 4], [4, 9, 14, 19, 24, 9, 14] ]
      dex_pilot: [None, None, None, None, None, ['<=', 0.015, 1e-4, 200], ['<=', 0.015, 1e-4, 200]]

      mimic:
        parent_joints: [ "R_thumb_proximal_pitch_joint", "R_thumb_proximal_pitch_joint", "R_index_proximal_joint", "R_middle_proximal_joint", "R_ring_proximal_joint", "R_pinky_proximal_joint" ]
        child_joints: [ "R_thumb_intermediate_joint", "R_thumb_distal_joint", "R_index_intermediate_joint", "R_middle_intermediate_joint", "R_ring_intermediate_joint", "R_pinky_intermediate_joint" ]
        mimic_factors: [ 1.6, 2.4, 1, 1, 1, 1 ]

