robot_cfg:
  name: jaxon
  urdf_path: jaxon/urdf/jaxon_jvrc.urdf
  body_indices: [0, 1, 2, 3, 4, 5, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]
  left_arm_indices: [6, 7, 8, 9, 10, 11, 12, 13]
  right_arm_indices: [16, 17, 18, 19, 20, 21, 22, 23]
  left_hand_indices: [14, 15]
  right_hand_indices: [24, 25]

  head_pos: [ 0.2, 0.0, 0.6 ]
  left_wrist_name: LARM_KEYPOINT
  right_wrist_name: RARM_KEYPOINT

  body:
    in_lp_alpha: 0.9

  arm:
    dt: 0.016667

    scaling_factor: 1.1
    base_damping: 1e-4
    max_damping: 1e-2
    eps: 1e-2

    in_lp_alpha: 0.5
    out_lp_alpha: 0.5

  hand:
    left_hand:
      scaling_factor: 2.0
      in_lp_alpha: 0.5
      out_lp_alpha: 0.5

      target_origin_link_names: [ "LARM_FINGER0_TIP" ]
      target_task_link_names: [ "LARM_FINGER1_TIP" ]
      target_link_human_indices: [ [ 4 ], [ 9 ] ]

      mimic:
        parent_joints: [ "LARM_F_JOINT0" ]
        child_joints: [ "LARM_F_JOINT1" ]
        mimic_factors: [ -1 ]

    right_hand:
      scaling_factor: 2.0
      in_lp_alpha: 0.5
      out_lp_alpha: 0.5

      target_origin_link_names: [ "RARM_FINGER0_TIP" ]
      target_task_link_names: [ "RARM_FINGER1_TIP" ]
      target_link_human_indices: [ [ 4 ], [ 9 ] ]

      mimic:
        parent_joints: [ "RARM_F_JOINT0" ]
        child_joints: [ "RARM_F_JOINT1" ]
        mimic_factors: [ -1 ]
