robot_cfg:
  name: valkyrie
  urdf_path: valkyrie/robots/valkyrie_A.urdf
  body_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 35, 36, 37]
  left_arm_indices: [15, 16, 17, 18, 19, 20, 21]
  right_arm_indices: [38, 39, 40, 41, 42, 43, 44]
  left_hand_indices: [ 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34 ]
  right_hand_indices: [ 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57 ]

  head_pos: [ 0.2, 0.0, 0.5 ]
  left_wrist_name: left_hand_keypoint
  right_wrist_name: right_hand_keypoint

  body:
    in_lp_alpha: 0.9

  arm:
    dt: 0.016667

    scaling_factor: 1.1
    base_damping: 1e-4
    max_damping: 1e-2
    eps: 1e-2

    in_lp_alpha: 0.5
    out_lp_alpha: 0.5

  hand:
    left_hand:
      scaling_factor: 1.2
      in_lp_alpha: 0.5
      out_lp_alpha: 0.5

      target_origin_link_names: [ "leftPalm", "leftPalm", "leftPalm", "leftPalm" ]
      target_task_link_names: [ "leftThumbTip",  "leftIndexFingerTip", "leftMiddleFingerTip", "leftPinkyTip" ]
      target_link_human_indices: [ [0, 0, 0, 0], [4, 9, 14, 19] ]

    right_hand:
      scaling_factor: 1.2
      in_lp_alpha: 0.5
      out_lp_alpha: 0.5

      target_origin_link_names: [ "rightPalm", "rightPalm", "rightPalm", "rightPalm" ]
      target_task_link_names: [ "rightThumbTip",  "rightIndexFingerTip", "rightMiddleFingerTip", "rightPinkyTip" ]
      target_link_human_indices: [ [0, 0, 0, 0], [4, 9, 14, 19] ]

