robot_cfg:
  name: xarm7_ability
  urdf_path: xarm7_ability/xarm7_ability.urdf
  body_indices: []
  left_arm_indices: [0, 1, 2, 3, 4, 5, 6]
  right_arm_indices: [17, 18, 19, 20, 21, 22, 23]
  left_hand_indices: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
  right_hand_indices: [24, 25, 26, 27, 28, 29, 30, 31, 32, 33]

  head_pos: [ 0.2, 0.0, 0.5 ]
  left_wrist_name: l_hand_keypoint
  right_wrist_name: r_hand_keypoint

  body:
    in_lp_alpha: 0.9
    in_lp_alpha: 0.9

  arm:
    dt: 0.016667

    scaling_factor: 1.5
    base_damping: 1e-4
    max_damping: 1e-2
    eps: 1e-2

    in_lp_alpha: 0.5
    out_lp_alpha: 0.5

  hand:
    left_hand:
      scaling_factor: 1.0
      in_lp_alpha: 0.5
      out_lp_alpha: 0.5

      target_origin_link_names: [ "l_hand_keypoint", "l_hand_keypoint", "l_hand_keypoint", "l_hand_keypoint", "l_hand_keypoint" ]
      target_task_link_names: [ "l_thumb_tip",  "l_index_tip", "l_middle_tip", "l_ring_tip", "l_pinky_tip" ]
      target_link_human_indices: [ [0, 0, 0, 0, 0], [4, 9, 14, 19, 24] ]

      mimic:
        parent_joints: [ "l_index_q1", "l_middle_q1", "l_ring_q1", "l_pinky_q1" ]
        child_joints: [ "l_index_q2", "l_middle_q2", "l_ring_q2", "l_pinky_q2" ]
        mimic_factors: [ 1.05851325, 1.05851325, 1.05851325, 1.05851325 ]

    right_hand:
      scaling_factor: 1.0
      in_lp_alpha: 0.5
      out_lp_alpha: 0.5

      target_origin_link_names: [ "r_hand_keypoint", "r_hand_keypoint", "r_hand_keypoint", "r_hand_keypoint", "r_hand_keypoint" ]
      target_task_link_names: [ "r_thumb_tip",  "r_index_tip", "r_middle_tip", "r_ring_tip", "r_pinky_tip" ]
      target_link_human_indices: [ [0, 0, 0, 0, 0], [4, 9, 14, 19, 24] ]

      mimic:
        parent_joints: [ "r_index_q1", "r_middle_q1", "r_ring_q1", "r_pinky_q1" ]
        child_joints: [ "r_index_q2", "r_middle_q2", "r_ring_q2", "r_pinky_q2" ]
        mimic_factors: [ 1.05851325, 1.05851325, 1.05851325, 1.05851325 ]
